# 优化版本 - 加快部署速度
# kube-prometheus-stack values for ALB integration

# 全局配置
global:
  imagePullSecrets: []

# Grafana 配置
grafana:
  enabled: true
  admin:
    existingSecret: "grafana-admin-secret"
    userKey: "admin-user"
    passwordKey: "admin-password"
  
  # 优化镜像配置
  image:
    repository: grafana/grafana
    tag: "9.5.2"
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  
  ingress:
    enabled: false
  
  # 首次部署禁用持久化以加快启动
  persistence:
    enabled: false
  
  # 禁用 sidecar 以加快启动
  sidecar:
    dashboards:
      enabled: false
    datasources:
      enabled: false
  
  # 优化资源请求
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Prometheus 配置
prometheus:
  enabled: true
  
  service:
    type: ClusterIP
    port: 9090
    targetPort: 9090
  
  ingress:
    enabled: false
  
  prometheusSpec:
    # 优化配置
    scrapeInterval: 60s
    evaluationInterval: 60s
    retention: 2d
    retentionSize: "5GB"
    
    # 减少副本数
    replicas: 1
    
    # 首次部署禁用持久化
    storageSpec: {}
    
    # 优化资源请求
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    
    # 简化服务发现
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}

# Alertmanager 配置
alertmanager:
  enabled: true
  
  service:
    type: ClusterIP
    port: 9093
    targetPort: 9093
  
  ingress:
    enabled: false
  
  alertmanagerSpec:
    # 减少副本数
    replicas: 1
    
    # 禁用持久化
    storage: {}
    
    # 优化资源请求
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "250m"

# 禁用非核心组件以加快部署
kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

# 核心监控组件（保持启用）
kubeApiServer:
  enabled: true

kubelet:
  enabled: true

coreDns:
  enabled: true

kubeStateMetrics:
  enabled: true
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

nodeExporter:
  enabled: true
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# 默认规则
defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: false  # 禁用 etcd 规则
    general: true
    k8s: true
    kubeApiserverAvailability: true
    kubelet: true
    node: true
    prometheus: true

# Operator 配置
prometheusOperator:
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "300m"
  
  # 优化镜像配置
  image:
    repository: prometheus-operator/prometheus-operator
    tag: "v0.68.0"
    pullPolicy: IfNotPresent

  # 禁用 admission webhook 以加快启动
  admissionWebhooks:
    enabled: false